modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="starwarsverse"
version="1.0.0"
displayName="starwarsverse"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="OEM, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.starwarsverse]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="AFTER"
side="BOTH"

[[dependencies.starwarsverse]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"


[[dependencies.starwarsverse]]
modId="geckolib"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"
[[dependencies.starwarsverse]]
modId="playeranimator"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"


[[mixins]]
    config="mixins.starwarsverse.json"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration